spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.coda.ao@gmail.com
    password: oezofnqvyrsptrzy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9095
  servlet:
    context-path: /meal/api/v1
  forward-headers-strategy: framework

logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs



management:
  security:
    enabled: false
  endpoint:
    metrics:
      access: read_only
    prometheus:
      access: read_only
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      access: read_only
    info:
      env:
        enabled: true
      access: read_only
  endpoints:
    web:
      {
        exposure:
          { include: prometheus, metrics, info, health, shutdown, beans },
      }

# Minio
minio:
  url: https://minio.apis-cinapse.com
  access:
    key: 11qhrfeb5eau0bps
  secret:
    key: ybasmig5jvt9dg8l97giavnzggx7ghrr
  region: "us-east-1"
  s3:
    api: "s3v4"
    path: "auto"
  bucket:
    main: reciclame-generic
    icons: reciclame-icons
  from: "dvml"

app:
  backend:
    url: https://something.com

# WeSender
wesender:
  sms:
    token: e5f4b10c0c464493bc3a98dad3dfc746d9d71734957d440eab7809d22a40ddf9
    api: https://api.wesender.co.ao/envio/apikey

identity:
  validation: "http://consulta.edgarsingui.ao/consultar/"
