spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:./data/mydb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: false

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: true